import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Cadence design-system palette (from DESIGN.md / Stitch exports)
        "surface":                    "#0b1326",
        "surface-dim":                "#0b1326",
        "surface-bright":             "#31394d",
        "surface-container-lowest":   "#060e20",
        "surface-container-low":      "#131b2e",
        "surface-container":          "#171f33",
        "surface-container-high":     "#222a3d",
        "surface-container-highest":  "#2d3449",
        "surface-variant":            "#2d3449",
        "surface-tint":               "#ddb7ff",
        "on-surface":                 "#dae2fd",
        "on-surface-variant":         "#cfc2d6",
        "inverse-surface":            "#dae2fd",
        "inverse-on-surface":         "#283044",
        "background":                 "#0b1326",
        "on-background":              "#dae2fd",
        "outline":                    "#988d9f",
        "outline-variant":            "#4d4354",
        // Primary — Electric Amethyst
        "primary":                    "#ddb7ff",
        "on-primary":                 "#490080",
        "primary-container":          "#b76dff",
        "on-primary-container":       "#400071",
        "inverse-primary":            "#842bd2",
        "primary-fixed":              "#f0dbff",
        "primary-fixed-dim":          "#ddb7ff",
        "on-primary-fixed":           "#2c0051",
        "on-primary-fixed-variant":   "#6900b3",
        // Secondary — Teal Pulse
        "secondary":                  "#4fdbc8",
        "on-secondary":               "#003731",
        "secondary-container":        "#04b4a2",
        "on-secondary-container":     "#003f38",
        "secondary-fixed":            "#71f8e4",
        "secondary-fixed-dim":        "#4fdbc8",
        "on-secondary-fixed":         "#00201c",
        "on-secondary-fixed-variant": "#005048",
        // Tertiary — Pink accent
        "tertiary":                   "#ffafd3",
        "on-tertiary":                "#620040",
        "tertiary-container":         "#e364a7",
        "on-tertiary-container":      "#560038",
        "tertiary-fixed":             "#ffd8e7",
        "tertiary-fixed-dim":         "#ffafd3",
        "on-tertiary-fixed":          "#3d0026",
        "on-tertiary-fixed-variant":  "#85145a",
        // Error
        "error":                      "#ffb4ab",
        "on-error":                   "#690005",
        "error-container":            "#93000a",
        "on-error-container":         "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm:      "0.25rem",
        md:      "0.75rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        "2xl":   "1rem",
        "3xl":   "1.5rem",
        full:    "9999px",
      },
      spacing: {
        xs:                "4px",
        sm:                "8px",
        md:                "16px",
        lg:                "24px",
        xl:                "48px",
        "2xl":             "80px",
        gutter:            "24px",
        "margin-mobile":   "16px",
        "margin-desktop":  "64px",
      },
      fontFamily: {
        // Reference the CSS variables injected by next/font/google so the font
        // always resolves whether or not the external request has completed.
        display:              ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        "headline-lg":        ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        "headline-lg-mobile": ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        "headline-md":        ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        "label-md":           ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        "mono-label":         ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        "body-lg":            ["var(--font-inter)", "Inter", "sans-serif"],
        "body-md":            ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        "display":             ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg":         ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-lg-mobile":  ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md":         ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "body-lg":             ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md":             ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md":            ["14px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "600" }],
        "mono-label":          ["12px", { lineHeight: "1.0", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
export default config;
